import React, { createContext, useContext, useState, useEffect } from 'react';

// Dictionary of translations for all supported languages (19 languages)
export const TRANSLATIONS = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    dir: 'ltr',
    brandSubtitle: 'Real-Time Emergency Response & Safety System',
    residentSOS: 'Resident SOS',
    respondersSecurity: 'Responders & Security',
    guardians: 'Guardians',
    caregiverRoster: 'Caregiver Roster',
    adminAnalytics: 'Admin Analytics',
    neighborPortal: 'Neighbor Network',
    introPage: '🎬 Intro Page',
    aiAssistant: 'AI Assistant',
    logout: 'Logout',
    welcome: 'Welcome',
    emergencyLocation: 'Emergency Location',
    describeEmergencyPlaceholder: 'Describe emergency (e.g. Fell in bathroom)...',
    aiClassify: 'AI Classify',
    triggerSOS: 'SOS',
    personalProfile: 'Personal & Medical Profile',
    fullName: 'Full Name',
    ageBloodGroup: 'Age / Blood Group',
    roomNumber: 'Registered Address',
    medicalNotes: 'Medical Condition & Notes',
    linkedGuardians: 'Linked Emergency Guardians',
    addGuardian: 'Add Guardian',
    emergencyHistory: 'Emergency Incident History',
    expandMap: 'Expand Map ⤢',
    minimizeMap: 'Minimize Map ⤪',
    mapTitle: 'Live Safety Map',
    roadMap: 'Roadmap',
    satellite: 'Satellite',
    darkMode: 'Dark Mode',
    centerGPS: 'Center GPS',
    emergencyDetected: 'EMERGENCY DETECTED',
    helpOnTheWay: 'HELP ON THE WAY',
    acceptIncident: 'Accept Incident Ticket',
    markResolved: 'Mark as Resolved',
    statusPending: 'PENDING',
    statusAccepted: 'ACCEPTED',
    statusResolved: 'RESOLVED',
    activeIncidents: 'Active Emergency Tickets',
    portalQuickAccess: 'Direct Portal Quick Access',
    residentPortal: 'Resident Portal',
    securityResponder: 'Security Responder',
    guardianPortal: 'Guardian Portal',
    volunteerPortal: 'Volunteer Portal',
    caregiverPortal: 'Caregiver Portal',
    adminPortal: 'Admin Portal',
    sensorTelemetry: 'IoT Smart Sensor Telemetry',
    simulateFall: '⚡ Simulate Sudden Fall',
    simulatePulseSpike: '❤️ Simulate Pulse Spike',
    neighborTagline: 'Every Second Matters. Every Neighbor Can Help.',
    signInTitle: 'CareConnect Login',
    signInSubtitle: 'Select a portal role or log in with credentials',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    loginBtn: 'Sign In to Portal',
    alreadyHaveAccount: 'Already registered? Log In',
    needAccount: 'Need an account? Register',
    registerBtn: 'Register',
    backToIntro: 'Back to Intro Screen',
    locating: 'Locating GPS...',
    locationOff: 'Location Off',
    refreshLocation: 'Refresh GPS Location',
    enableLocation: 'Enable Live GPS Location',
    locationStatus: 'Live Location Status',
    addressLabel: 'Address:',
    coordinatesLabel: 'Coordinates:',
    accuracyLabel: 'Accuracy:'
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिंदी',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'वास्तविक समय आपातकालीन प्रतिक्रिया और सुरक्षा प्रणाली',
    residentSOS: 'निवासी एसओएस (SOS)',
    respondersSecurity: 'सुरक्षा दल और प्रतिक्रियाकर्ता',
    guardians: 'अभिभावक (Guardians)',
    caregiverRoster: 'देखभालकर्ता सूची',
    adminAnalytics: 'प्रशासन विश्लेषण',
    neighborPortal: 'पड़ोसी नेटवर्क',
    introPage: '🎬 परिचय वीडियो',
    aiAssistant: 'एआई सहायक',
    logout: 'लॉग आउट',
    welcome: 'स्वागत है',
    emergencyLocation: 'आपातकालीन स्थान',
    describeEmergencyPlaceholder: 'आपात स्थिति का वर्णन करें...',
    aiClassify: 'एआई वर्गीकरण',
    triggerSOS: 'एसओएस भेजें',
    personalProfile: 'व्यक्तिगत एवं चिकित्सा प्रोफ़ाइल',
    fullName: 'पूरा नाम',
    ageBloodGroup: 'आयु / रक्त समूह',
    roomNumber: 'पंजीकृत पता',
    medicalNotes: 'चिकित्सा स्थिति एवं नोट्स',
    linkedGuardians: 'जुड़े आपातकालीन अभिभावक',
    addGuardian: 'अभिभावक जोड़ें',
    emergencyHistory: 'आपातकालीन घटना इतिहास',
    expandMap: 'नक्शा बड़ा करें ⤢',
    minimizeMap: 'नक्शा छोटा करें ⤪',
    mapTitle: 'लाइव सुरक्षा नक्शा',
    roadMap: 'सड़क का नक्शा',
    satellite: 'सैटेलाइट View',
    darkMode: 'डार्क मोड',
    centerGPS: 'जीपीएस केंद्र',
    emergencyDetected: 'आपात स्थिति पता चली',
    helpOnTheWay: 'मदद रास्ते में है',
    acceptIncident: 'घटना स्वीकार करें',
    markResolved: 'हल के रूप में चिह्नित करें',
    statusPending: 'लंबित',
    statusAccepted: 'स्वीकृत',
    statusResolved: 'हल किया गया',
    activeIncidents: 'सक्रिय आपातकालीन मामले',
    portalQuickAccess: 'पोर्टल त्वरित पहुँच',
    residentPortal: 'निवासी पोर्टल',
    securityResponder: 'सुरक्षा प्रतिक्रियाकर्ता',
    guardianPortal: 'अभिभावक पोर्टल',
    volunteerPortal: 'स्वयंसेवक पोर्टल',
    caregiverPortal: 'देखभालकर्ता पोर्टल',
    adminPortal: 'प्रशासन पोर्टल',
    sensorTelemetry: 'आईओटी स्मार्ट सेंसर टेलीमेट्री',
    simulateFall: '⚡ अचानक गिरने का सिमुलेशन करें',
    simulatePulseSpike: '❤️ नाड़ी वृद्धि का सिमुलेशन करें',
    neighborTagline: 'हर सेकंड महत्वपूर्ण है। हर पड़ोसी मदद कर सकता है।',
    signInTitle: 'केयरकनेक्ट लॉगिन',
    signInSubtitle: 'एक पोर्टल भूमिका चुनें या क्रेडेंशियल से लॉगिन करें',
    emailLabel: 'ईमेल पता',
    passwordLabel: 'पासवर्ड',
    loginBtn: 'पोर्टल में साइन इन करें',
    alreadyHaveAccount: 'पहले से पंजीकृत हैं? लॉगिन करें',
    needAccount: 'खाता चाहिए? पंजीकरण करें',
    registerBtn: 'पंजीकरण करें',
    backToIntro: 'परिचय स्क्रीन पर वापस जाएं',
    locating: 'जीपीएस का पता लगाया जा रहा है...',
    locationOff: 'स्थान बंद है',
    refreshLocation: 'जीपीएस स्थान रिफ्रेश करें',
    enableLocation: 'लाइव जीपीएस चालू करें',
    locationStatus: 'लाइव स्थान स्थिति',
    addressLabel: 'पता:',
    coordinatesLabel: 'निर्देशांक:',
    accuracyLabel: 'सटीकता:'
  },
  te: {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'రియల్ టైమ్ అత్యవసర స్పందన & రక్షణ వ్యవస్థ',
    residentSOS: 'నివాసి SOS',
    respondersSecurity: 'భద్రతా విభాగం',
    guardians: 'సంరక్షకులు',
    caregiverRoster: 'సంరక్షణ సిబ్బంది',
    adminAnalytics: 'అడ్మిన్ విశ్లేషణ',
    neighborPortal: 'పొరుగు నెట్‌వర్క్',
    introPage: '🎬 పరిచయం',
    aiAssistant: 'AI సహాయకుడు',
    logout: 'లాగ్ అవుట్',
    welcome: 'స్వాగతం',
    emergencyLocation: 'అత్యవసర స్థానం',
    describeEmergencyPlaceholder: 'అత్యవసర పరిస్థితిని వివరించండి...',
    aiClassify: 'AI వర్గీకరణ',
    triggerSOS: 'SOS ప్రారంభించు',
    personalProfile: 'వ్యక్తిగత & వైద్య ప్రొఫైల్',
    fullName: 'పూర్తి పేరు',
    ageBloodGroup: 'వయస్సు / రక్త గ్రూపు',
    roomNumber: 'నమోదిత చిరునామా',
    medicalNotes: 'వైద్య సమస్యలు & గమనికలు',
    linkedGuardians: 'అత్యవసర సంరక్షకులు',
    addGuardian: 'సంరక్షకుడిని జోడించండి',
    emergencyHistory: 'అత్యవసర సమాచార చరిత్ర',
    expandMap: 'మ్యాప్ విప్పండి ⤢',
    minimizeMap: 'మ్యాప్ చిన్నది చేయండి ⤪',
    mapTitle: 'లైవ్ రక్షణ మ్యాప్',
    roadMap: 'రోడ్డు మ్యాప్',
    satellite: 'శాటిలైట్',
    darkMode: 'డార్క్ మోడ్',
    centerGPS: 'GPS కేంద్రీకరించు',
    emergencyDetected: 'అత్యవసర పరిస్థితి గుర్తించబడింది',
    helpOnTheWay: 'సహాయం వస్తోంది',
    acceptIncident: 'కేసు అంగీకరించు',
    markResolved: 'పూర్తయినట్లు గుర్తించు',
    statusPending: 'పెండింగ్',
    statusAccepted: 'అంగీకరించబడింది',
    statusResolved: 'పరిష్కరించబడింది',
    activeIncidents: 'యాక్టివ్ కేసులు',
    portalQuickAccess: 'పోర్టల్స్ క్విక్ యాక్సెస్',
    residentPortal: 'నివాసి పోర్టల్',
    securityResponder: 'సెక్యూరిటీ రెస్పాండర్',
    guardianPortal: 'గార్డియన్ పోర్టల్',
    volunteerPortal: 'వాలంటీర్ పోర్టల్',
    caregiverPortal: 'సంరక్షకుని పోర్టల్',
    adminPortal: 'అడ్మిన్ పోర్టల్',
    sensorTelemetry: 'IoT స్మార్ట్ సెన్సార్ టెలిమెట్రీ',
    simulateFall: '⚡ కిందపడటం అనుకరించండి',
    simulatePulseSpike: '❤️ పల్స్ పెరుగుదల అనుకరించండి',
    neighborTagline: 'ప్రతి క్షణం ముఖ్యం. ప్రతి పొరుగువాడు సహాయపడగలడు.',
    signInTitle: 'కేర్‌కనెక్ట్ లాగిన్',
    signInSubtitle: 'లాగిన్ వివరాలను నమోదు చేయండి',
    emailLabel: 'ఈమెయిల్ చిరునామా',
    passwordLabel: 'పాస్‌వర్డ్',
    loginBtn: 'సైన్ ఇన్ చేయండి',
    alreadyHaveAccount: 'ఖాతా ఉందా? లాగిన్ అవ్వండి',
    needAccount: 'ఖాతా లేదా? నమోదు చేసుకోండి',
    registerBtn: 'నమోదు చేయండి',
    backToIntro: 'పరిచయ వీడియోకి తిరిగి వెళ్ళండి',
    locating: 'GPS గుర్తిస్తోంది...',
    locationOff: 'స్థానం ఆఫ్‌లో ఉంది',
    refreshLocation: 'GPS రిఫ్రెష్ చేయండి',
    enableLocation: 'GPS ప్రారంభించండి',
    locationStatus: 'లైవ్ GPS వివరాలు',
    addressLabel: 'చిరునామా:',
    coordinatesLabel: 'కోఆర్డినేట్లు:',
    accuracyLabel: 'ఖచ్చితత్వం:'
  },
  ta: {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'நிகழ்நேர அவசர உதவி மற்றும் பாதுகாப்பு அமைப்பு',
    residentSOS: 'குடியிருப்பாளர் SOS',
    respondersSecurity: 'பாதுகாப்புப் படை',
    guardians: 'பாதுகாவலர்கள்',
    caregiverRoster: 'பராமரிப்பாளர் பட்டியல்',
    adminAnalytics: 'நிர்வாக பகுப்பாய்வு',
    neighborPortal: 'அண்டை வீட்டார் நெட்வொர்க்',
    introPage: '🎬 அறிமுகம்',
    aiAssistant: 'AI உதவியாளர்',
    logout: 'வெளியேறு',
    welcome: 'நல்வரவு',
    emergencyLocation: 'அவசர இடம்',
    describeEmergencyPlaceholder: 'அவசரநிலையை விவரிக்கவும்...',
    aiClassify: 'AI வகைப்பாடு',
    triggerSOS: 'SOS அனுப்பு',
    personalProfile: 'தனிப்பட்ட & மருத்துவப் விபரம்',
    fullName: 'முழு பெயர்',
    ageBloodGroup: 'வயது / ரத்த வகை',
    roomNumber: 'பதிவு செய்யப்பட்ட முகவரி',
    medicalNotes: 'மருத்துவ குறிப்புகள்',
    linkedGuardians: 'இணைக்கப்பட்ட பாதுகாவலர்கள்',
    addGuardian: 'பாதுகாவலரைச் சேர்',
    emergencyHistory: 'அவசர சம்பவ வரலாறு',
    expandMap: 'வரைபடத்தை பெரிதாக்கு ⤢',
    minimizeMap: 'வரைபடத்தை சிறிதாக்கு ⤪',
    mapTitle: 'பாதுகாப்பு வரைபடம்',
    roadMap: 'சாலை வரைபடம்',
    satellite: 'செயற்கைக்கோள்',
    darkMode: 'டார்க் மோட்',
    centerGPS: 'GPS மையம்',
    emergencyDetected: 'அவசரநிலை கண்டறியப்பட்டது',
    helpOnTheWay: 'உதவி வருகிறது',
    acceptIncident: 'ஏற்றுக்கொள்',
    markResolved: 'முடிந்தது என குறி',
    statusPending: 'நிலுவையில்',
    statusAccepted: 'ஏற்கப்பட்டது',
    statusResolved: 'தீர்வு காணப்பட்டது',
    activeIncidents: 'செயலில் உள்ள அவசரநிலைகள்',
    portalQuickAccess: 'விரைவு அணுகல்',
    residentPortal: 'குடியிருப்பாளர் போர்டல்',
    securityResponder: 'பாதுகாப்பு போர்டல்',
    guardianPortal: 'பாதுகாவலர் போர்டல்',
    volunteerPortal: 'தன்னார்வலர் போர்டல்',
    caregiverPortal: 'பராமரிப்பாளர் போர்டல்',
    adminPortal: 'நிர்வாக போர்டல்',
    sensorTelemetry: 'IoT ஸ்மார்ட் சென்சார்',
    simulateFall: '⚡ வீழ்ச்சியை உருவகப்படுத்து',
    simulatePulseSpike: '❤️ இதய துடிப்பை உருவகப்படுத்து',
    neighborTagline: 'ஒவ்வொரு நொடியும் முக்கியம். அண்டை வீட்டார் உதவலாம்.',
    signInTitle: 'CareConnect உள்நுழைவு',
    signInSubtitle: 'உங்கள் விவரங்களை உள்ளிடவும்',
    emailLabel: 'மின்னஞ்சல்',
    passwordLabel: 'கடவுச்சொல்',
    loginBtn: 'உள்நுழை',
    alreadyHaveAccount: 'கணக்கு உள்ளதா? உள்நுழை',
    needAccount: 'கணக்கு தேவையா? பதிவு செய்',
    registerBtn: 'பதிவு செய்',
    backToIntro: 'அறிமுகத் திரைக்குத் திரும்பு',
    locating: 'GPS கண்டறியப்படுகிறது...',
    locationOff: 'இருப்பிடம் முடங்கியுள்ளது',
    refreshLocation: 'GPS புதுப்பி',
    enableLocation: 'GPS இயக்கு',
    locationStatus: 'இருப்பிட நிலை',
    addressLabel: 'முகவரி:',
    coordinatesLabel: 'ஆயத்தொலைவுகள்:',
    accuracyLabel: 'துல்லியம்:'
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    dir: 'ltr',
    brandSubtitle: 'リアルタイム緊急通報＆安全管理システム',
    residentSOS: '居住者SOS',
    respondersSecurity: '警備・救護チーム',
    guardians: '保護者・ご家族',
    caregiverRoster: '介護スタッフ名簿',
    adminAnalytics: '管理者アナリティクス',
    neighborPortal: '地域助け合いネットワーク',
    introPage: '🎬 紹介動画',
    aiAssistant: 'AIアシスタント',
    logout: 'ログアウト',
    welcome: 'ようこそ',
    emergencyLocation: '発生場所',
    describeEmergencyPlaceholder: '状況を入力してください（例：浴室で転倒）...',
    aiClassify: 'AI分析',
    triggerSOS: 'SOS発信',
    personalProfile: 'カルテ・基本情報',
    fullName: '氏名',
    ageBloodGroup: '年齢 / 血液型',
    roomNumber: '登録住所',
    medicalNotes: '持病・特記事項',
    linkedGuardians: '緊急連絡先（ご家族）',
    addGuardian: '連絡先を追加',
    emergencyHistory: '緊急対応履歴',
    expandMap: 'マップ拡大 ⤢',
    minimizeMap: 'マップ縮小 ⤪',
    mapTitle: 'リアルタイム安全マップ',
    roadMap: '標準地図',
    satellite: '航空写真',
    darkMode: 'ダークモード',
    centerGPS: '現在地に移動',
    emergencyDetected: '緊急事態発生',
    helpOnTheWay: '救助に向かっています',
    acceptIncident: '対応を開始する',
    markResolved: '対応完了とする',
    statusPending: '対応待ち',
    statusAccepted: '対応中',
    statusResolved: '解決済み',
    activeIncidents: '発生中の緊急案件',
    portalQuickAccess: 'ポータルクイック切替',
    residentPortal: '居住者ポータル',
    securityResponder: '警備・救護ポータル',
    guardianPortal: 'ご家族ポータル',
    volunteerPortal: 'ボランティア',
    caregiverPortal: '介護スタッフ',
    adminPortal: '管理者ポータル',
    sensorTelemetry: 'IoTバイタルセンサー',
    simulateFall: '⚡ 転倒検知テスト',
    simulatePulseSpike: '❤️ 脈拍異常テスト',
    neighborTagline: '一秒を争う命。地域の助け合いが力に。',
    signInTitle: 'CareConnect ログイン',
    signInSubtitle: '役割を選択するかログイン情報を入力してください',
    emailLabel: 'メールアドレス',
    passwordLabel: 'パスワード',
    loginBtn: 'ログイン',
    alreadyHaveAccount: 'アカウントをお持ちの方はこちら',
    needAccount: '新規登録はこちら',
    registerBtn: '新規登録',
    backToIntro: 'イントロ画面に戻る',
    locating: '位置情報を取得中...',
    locationOff: '位置情報オフ',
    refreshLocation: 'GPS再取得',
    enableLocation: '位置情報を有効化',
    locationStatus: '位置情報ステータス',
    addressLabel: '住所:',
    coordinatesLabel: '座標:',
    accuracyLabel: '精度:'
  },
  zh: {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    flag: '🇨🇳',
    dir: 'ltr',
    brandSubtitle: '实时紧急呼叫与安全防护系统',
    residentSOS: '居民 SOS 呼救',
    respondersSecurity: '安保与救援队',
    guardians: '家属 Guardian',
    caregiverRoster: '护理人员名册',
    adminAnalytics: '管理后台分析',
    neighborPortal: '邻里互助网络',
    introPage: '🎬 介绍视频',
    aiAssistant: 'AI 智能助手',
    logout: '退出登录',
    welcome: '欢迎',
    emergencyLocation: '事发地点',
    describeEmergencyPlaceholder: '请描述紧急情况...',
    aiClassify: 'AI 快速分类',
    triggerSOS: '发起 SOS',
    personalProfile: '个人与健康档案',
    fullName: '姓名',
    ageBloodGroup: '年龄 / 血型',
    roomNumber: '登记地址',
    medicalNotes: '病史及注意事项',
    linkedGuardians: '关联紧急联系人',
    addGuardian: '添加联系人',
    emergencyHistory: '历史报警记录',
    expandMap: '放大地图 ⤢',
    minimizeMap: '缩小地图 ⤪',
    mapTitle: '实时安全地图',
    roadMap: '标准路线图',
    satellite: '卫星图',
    darkMode: '暗黑模式',
    centerGPS: '定位至当前点',
    emergencyDetected: '检测到紧急呼救',
    helpOnTheWay: '救援人员正在赶来',
    acceptIncident: '接单救援',
    markResolved: '标记为已完成',
    statusPending: '待处理',
    statusAccepted: '救援中',
    statusResolved: '已解决',
    activeIncidents: '当前紧急案件',
    portalQuickAccess: '快捷入口',
    residentPortal: '居民端',
    securityResponder: '安保端',
    guardianPortal: '家属端',
    volunteerPortal: '志愿者端',
    caregiverPortal: '护理端',
    adminPortal: '管理端',
    sensorTelemetry: 'IoT 智能手环遥测',
    simulateFall: '⚡ 模拟跌倒警报',
    simulatePulseSpike: '❤️ 模拟心率异常',
    neighborTagline: '分秒必争，邻里相助。',
    signInTitle: 'CareConnect 登录',
    signInSubtitle: '选择角色快捷登录或输入账号',
    emailLabel: '邮箱地址',
    passwordLabel: '密码',
    loginBtn: '登录系统',
    alreadyHaveAccount: '已有账号？直接登录',
    needAccount: '没有账号？立即注册',
    registerBtn: '注册',
    backToIntro: '返回介绍页面',
    locating: '正在定位中...',
    locationOff: '未开启定位',
    refreshLocation: '刷新 GPS 定位',
    enableLocation: '开启实时 GPS',
    locationStatus: '定位状态',
    addressLabel: '当前地址:',
    coordinatesLabel: '经纬度:',
    accuracyLabel: '精度:'
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    dir: 'ltr',
    brandSubtitle: '실시간 응급 대응 및 안전 관리 시스템',
    residentSOS: '입주자 SOS',
    respondersSecurity: '보안 및 구조대',
    guardians: '보호자',
    caregiverRoster: '간병인 명단',
    adminAnalytics: '관리자 분석',
    neighborPortal: '이웃 상부상조 네트워크',
    introPage: '🎬 소개 영상',
    aiAssistant: 'AI 비서',
    logout: '로그아웃',
    welcome: '환영합니다',
    emergencyLocation: '응급 발생 위치',
    describeEmergencyPlaceholder: '응급 상황을 입력하세요...',
    aiClassify: 'AI 분류',
    triggerSOS: 'SOS 요청',
    personalProfile: '개인 및 건강 프로필',
    fullName: '성명',
    ageBloodGroup: '연령 / 혈액형',
    roomNumber: '등록 주소',
    medicalNotes: '기저질환 및 메모',
    linkedGuardians: '등록된 비상 연락처',
    addGuardian: '보호자 추가',
    emergencyHistory: '응급 신고 이력',
    expandMap: '지도 확대 ⤢',
    minimizeMap: '지도 축소 ⤪',
    mapTitle: '실시간 안전 지도',
    roadMap: '일반 지도',
    satellite: '위성 지도',
    darkMode: '다크 모드',
    centerGPS: '내 위치 이동',
    emergencyDetected: '응급 상황 감지',
    helpOnTheWay: '구조대가 이동 중입니다',
    acceptIncident: '신고 수락',
    markResolved: '조치 완료',
    statusPending: '대기 중',
    statusAccepted: '처리 중',
    statusResolved: '완료됨',
    activeIncidents: '진행 중인 응급 사건',
    portalQuickAccess: '빠른 포털 이동',
    residentPortal: '입주자 포털',
    securityResponder: '보안 구조대',
    guardianPortal: '보호자 포털',
    volunteerPortal: '봉사자 포털',
    caregiverPortal: '간병인 포털',
    adminPortal: '관리자 포털',
    sensorTelemetry: 'IoT 스마트 바이탈 센서',
    simulateFall: '⚡ 낙상 시뮬레이션',
    simulatePulseSpike: '❤️ 심박수 이상 시뮬레이션',
    neighborTagline: '1초가 급한 순간, 이웃의 도움이 함께합니다.',
    signInTitle: 'CareConnect 로그인',
    signInSubtitle: '역할을 선택하거나 계정 정보를 입력하세요',
    emailLabel: '이메일 주소',
    passwordLabel: '비밀번호',
    loginBtn: '로그인',
    alreadyHaveAccount: '계정이 있으신가요? 로그인',
    needAccount: '계정이 없으신가요? 회원가입',
    registerBtn: '회원가입',
    backToIntro: '소개 화면으로 이동',
    locating: 'GPS 위치 확인 중...',
    locationOff: '위치 비활성화',
    refreshLocation: 'GPS 새로고침',
    enableLocation: 'GPS 활성화',
    locationStatus: '실시간 위치 상태',
    addressLabel: '주소:',
    coordinatesLabel: '좌표:',
    accuracyLabel: '오차范围:'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('careconnect_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('careconnect_lang', lang);
    const currentDict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    document.documentElement.dir = currentDict.dir || 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, currentLangObj: TRANSLATIONS[lang] || TRANSLATIONS.en }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
