import React, { createContext, useContext, useState, useEffect } from 'react';

// Dictionary of translations for all supported languages (19 languages)
export const TRANSLATIONS = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    dir: 'ltr',
    brandSubtitle: 'Real-Time Emergency Response & Safety System',
    residentSOS: 'Resident SOS',
    respondersSecurity: 'Responders & Security',
    guardians: 'Guardians',
    caregiverRoster: 'Caregiver Roster',
    adminAnalytics: 'Admin Analytics',
    neighborPortal: 'Neighbor Network',
    introPage: '🎬 Intro Page',
    aiAssistant: 'CarePulse AI',
    logout: 'Logout',
    welcome: 'Welcome',
    emergencyLocation: 'Emergency Location',
    describeEmergencyPlaceholder: 'Describe emergency (e.g. Fell in bathroom)...',
    aiClassify: 'AI Classify',
    triggerSOS: 'SOS',
    personalProfile: 'Personal & Medical Profile',
    fullName: 'Full Name',
    ageBloodGroup: 'Age / Blood Group',
    roomNumber: 'Registered Address',
    medicalNotes: 'Medical Condition & Notes',
    linkedGuardians: 'Linked Emergency Guardians',
    addGuardian: 'Add Guardian',
    emergencyHistory: 'Emergency Incident History',
    expandMap: 'Expand Map ⤢',
    minimizeMap: 'Minimize Map ⤪',
    mapTitle: 'Live Safety Map',
    roadMap: 'Roadmap',
    satellite: 'Satellite',
    darkMode: 'Dark Mode',
    centerGPS: 'Center GPS',
    emergencyDetected: 'EMERGENCY DETECTED',
    helpOnTheWay: 'HELP ON THE WAY',
    acceptIncident: 'Accept Incident Ticket',
    markResolved: 'Mark as Resolved',
    statusPending: 'PENDING',
    statusAccepted: 'ACCEPTED',
    statusResolved: 'RESOLVED',
    activeIncidents: 'Active Emergency Tickets',
    portalQuickAccess: 'Direct Portal Quick Access',
    residentPortal: 'Resident Portal',
    securityResponder: 'Security Responder',
    guardianPortal: 'Guardian Portal',
    volunteerPortal: 'Volunteer Portal',
    caregiverPortal: 'Caregiver Portal',
    adminPortal: 'Admin Portal',
    sensorTelemetry: 'IoT Smart Sensor Telemetry',
    simulateFall: '⚡ Simulate Sudden Fall',
    simulatePulseSpike: '❤️ Simulate Pulse Spike',
    neighborTagline: 'Every Second Matters. Every Neighbor Can Help.',
    signInTitle: 'CareConnect Login',
    signInSubtitle: 'Select a portal role or log in with credentials',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    loginBtn: 'Sign In to Portal',
    alreadyHaveAccount: 'Already registered? Log In',
    needAccount: 'Need an account? Register',
    registerBtn: 'Register',
    backToIntro: 'Back to Intro Screen',
    locating: 'Locating GPS...',
    locationOff: 'Location Off',
    refreshLocation: 'Refresh GPS Location',
    enableLocation: 'Enable Live GPS Location',
    locationStatus: 'Live Location Status',
    addressLabel: 'Address:',
    coordinatesLabel: 'Coordinates:',
    accuracyLabel: 'Accuracy:'
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिंदी',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'वास्तविक समय आपातकालीन प्रतिक्रिया और सुरक्षा प्रणाली',
    residentSOS: 'निवासी एसओएस (SOS)',
    respondersSecurity: 'सुरक्षा दल और प्रतिक्रियाकर्ता',
    guardians: 'अभिभावक (Guardians)',
    caregiverRoster: 'देखभालकर्ता सूची',
    adminAnalytics: 'प्रशासन विश्लेषण',
    neighborPortal: 'पड़ोसी नेटवर्क',
    introPage: '🎬 परिचय वीडियो',
    aiAssistant: 'एआई सहायक',
    logout: 'लॉग आउट',
    welcome: 'स्वागत है',
    emergencyLocation: 'आपातकालीन स्थान',
    describeEmergencyPlaceholder: 'आपात स्थिति का वर्णन करें...',
    aiClassify: 'एआई वर्गीकरण',
    triggerSOS: 'एसओएस भेजें',
    personalProfile: 'व्यक्तिगत एवं चिकित्सा प्रोफ़ाइल',
    fullName: 'पूरा नाम',
    ageBloodGroup: 'आयु / रक्त समूह',
    roomNumber: 'पंजीकृत पता',
    medicalNotes: 'चिकित्सा स्थिति एवं नोट्स',
    linkedGuardians: 'जुड़े आपातकालीन अभिभावक',
    addGuardian: 'अभिभावक जोड़ें',
    emergencyHistory: 'आपातकालीन घटना इतिहास',
    expandMap: 'नक्शा बड़ा करें ⤢',
    minimizeMap: 'नक्शा छोटा करें ⤪',
    mapTitle: 'लाइव सुरक्षा नक्शा',
    roadMap: 'सड़क का नक्शा',
    satellite: 'सैटेलाइट View',
    darkMode: 'डार्क मोड',
    centerGPS: 'जीपीएस केंद्र',
    emergencyDetected: 'आपात स्थिति पता चली',
    helpOnTheWay: 'मदद रास्ते में है',
    acceptIncident: 'घटना स्वीकार करें',
    markResolved: 'हल के रूप में चिह्नित करें',
    statusPending: 'लंबित',
    statusAccepted: 'स्वीकृत',
    statusResolved: 'हल किया गया',
    activeIncidents: 'सक्रिय आपातकालीन मामले',
    portalQuickAccess: 'पोर्टल त्वरित पहुँच',
    residentPortal: 'निवासी पोर्टल',
    securityResponder: 'सुरक्षा प्रतिक्रियाकर्ता',
    guardianPortal: 'अभिभावक पोर्टल',
    volunteerPortal: 'स्वयंसेवक पोर्टल',
    caregiverPortal: 'देखभालकर्ता पोर्टल',
    adminPortal: 'प्रशासन पोर्टल',
    sensorTelemetry: 'आईओटी स्मार्ट सेंसर टेलीमेट्री',
    simulateFall: '⚡ अचानक गिरने का सिमुलेशन करें',
    simulatePulseSpike: '❤️ नाड़ी वृद्धि का सिमुलेशन करें',
    neighborTagline: 'हर सेकंड महत्वपूर्ण है। हर पड़ोसी मदद कर सकता है।',
    signInTitle: 'केयरकनेक्ट लॉगिन',
    signInSubtitle: 'एक पोर्टल भूमिका चुनें या क्रेडेंशियल से लॉगिन करें',
    emailLabel: 'ईमेल पता',
    passwordLabel: 'पासवर्ड',
    loginBtn: 'पोर्टल में साइन इन करें',
    alreadyHaveAccount: 'पहले से पंजीकृत हैं? लॉगिन करें',
    needAccount: 'खाता चाहिए? पंजीकरण करें',
    registerBtn: 'पंजीकरण करें',
    backToIntro: 'परिचय स्क्रीन पर वापस जाएं',
    locating: 'जीपीएस का पता लगाया जा रहा है...',
    locationOff: 'स्थान बंद है',
    refreshLocation: 'जीपीएस स्थान रिफ्रेश करें',
    enableLocation: 'लाइव जीपीएस चालू करें',
    locationStatus: 'लाइव स्थान स्थिति',
    addressLabel: 'पता:',
    coordinatesLabel: 'निर्देशांक:',
    accuracyLabel: 'सटीकता:'
  },
  te: {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'రియల్ టైమ్ అత్యవసర స్పందన & రక్షణ వ్యవస్థ',
    residentSOS: 'నివాసి SOS',
    respondersSecurity: 'భద్రతా విభాగం',
    guardians: 'సంరక్షకులు',
    caregiverRoster: 'సంరక్షణ సిబ్బంది',
    adminAnalytics: 'అడ్మిన్ విశ్లేషణ',
    neighborPortal: 'పొరుగు నెట్‌వర్క్',
    introPage: '🎬 పరిచయం',
    aiAssistant: 'AI సహాయకుడు',
    logout: 'లాగ్ అవుట్',
    welcome: 'స్వాగతం',
    emergencyLocation: 'అత్యవసర స్థానం',
    describeEmergencyPlaceholder: 'అత్యవసర పరిస్థితిని వివరించండి...',
    aiClassify: 'AI వర్గీకరణ',
    triggerSOS: 'SOS ప్రారంభించు',
    personalProfile: 'వ్యక్తిగత & వైద్య ప్రొఫైల్',
    fullName: 'పూర్తి పేరు',
    ageBloodGroup: 'వయస్సు / రక్త గ్రూపు',
    roomNumber: 'నమోదిత చిరునామా',
    medicalNotes: 'వైద్య సమస్యలు & గమనికలు',
    linkedGuardians: 'అత్యవసర సంరక్షకులు',
    addGuardian: 'సంరక్షకుడిని జోడించండి',
    emergencyHistory: 'అత్యవసర సమాచార చరిత్ర',
    expandMap: 'మ్యాప్ విప్పండి ⤢',
    minimizeMap: 'మ్యాప్ చిన్నది చేయండి ⤪',
    mapTitle: 'లైవ్ రక్షణ మ్యాప్',
    roadMap: 'రోడ్డు మ్యాప్',
    satellite: 'శాటిలైట్',
    darkMode: 'డార్క్ మోడ్',
    centerGPS: 'GPS కేంద్రీకరించు',
    emergencyDetected: 'అత్యవసర పరిస్థితి గుర్తించబడింది',
    helpOnTheWay: 'సహాయం వస్తోంది',
    acceptIncident: 'కేసు అంగీకరించు',
    markResolved: 'పూర్తయినట్లు గుర్తించు',
    statusPending: 'పెండింగ్',
    statusAccepted: 'అంగీకరించబడింది',
    statusResolved: 'పరిష్కరించబడింది',
    activeIncidents: 'యాక్టివ్ కేసులు',
    portalQuickAccess: 'పోర్టల్స్ క్విక్ యాక్సెస్',
    residentPortal: 'నివాసి పోర్టల్',
    securityResponder: 'సెక్యూరిటీ రెస్పాండర్',
    guardianPortal: 'గార్డియన్ పోర్టల్',
    volunteerPortal: 'వాలంటీర్ పోర్టల్',
    caregiverPortal: 'సంరక్షకుని పోర్టల్',
    adminPortal: 'అడ్మిన్ పోర్టల్',
    sensorTelemetry: 'IoT స్మార్ట్ సెన్సార్ టెలిమెట్రీ',
    simulateFall: '⚡ కిందపడటం అనుకరించండి',
    simulatePulseSpike: '❤️ పల్స్ పెరుగుదల అనుకరించండి',
    neighborTagline: 'ప్రతి క్షణం ముఖ్యం. ప్రతి పొరుగువాడు సహాయపడగలడు.',
    signInTitle: 'కేర్‌కనెక్ట్ లాగిన్',
    signInSubtitle: 'లాగిన్ వివరాలను నమోదు చేయండి',
    emailLabel: 'ఈమెయిల్ చిరునామా',
    passwordLabel: 'పాస్‌వర్డ్',
    loginBtn: 'సైన్ ఇన్ చేయండి',
    alreadyHaveAccount: 'ఖాతా ఉందా? లాగిన్ అవ్వండి',
    needAccount: 'ఖాతా లేదా? నమోదు చేసుకోండి',
    registerBtn: 'నమోదు చేయండి',
    backToIntro: 'పరిచయ వీడియోకి తిరిగి వెళ్ళండి',
    locating: 'GPS గుర్తిస్తోంది...',
    locationOff: 'స్థానం ఆఫ్‌లో ఉంది',
    refreshLocation: 'GPS రిఫ్రెష్ చేయండి',
    enableLocation: 'GPS ప్రారంభించండి',
    locationStatus: 'లైవ్ GPS వివరాలు',
    addressLabel: 'చిరునామా:',
    coordinatesLabel: 'కోఆర్డినేట్లు:',
    accuracyLabel: 'ఖచ్చితత్వం:'
  },
  ta: {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'நிகழ்நேர அவசர உதவி மற்றும் பாதுகாப்பு அமைப்பு',
    residentSOS: 'குடியிருப்பாளர் SOS',
    respondersSecurity: 'பாதுகாப்புப் படை',
    guardians: 'பாதுகாவலர்கள்',
    caregiverRoster: 'பராமரிப்பாளர் பட்டியல்',
    adminAnalytics: 'நிர்வாக பகுப்பாய்வு',
    neighborPortal: 'அண்டை வீட்டார் நெட்வொர்க்',
    introPage: '🎬 அறிமுகம்',
    aiAssistant: 'AI உதவியாளர்',
    logout: 'வெளியேறு',
    welcome: 'நல்வரவு',
    emergencyLocation: 'அவசர இடம்',
    describeEmergencyPlaceholder: 'அவசரநிலையை விவரிக்கவும்...',
    aiClassify: 'AI வகைப்பாடு',
    triggerSOS: 'SOS அனுப்பு',
    personalProfile: 'தனிப்பட்ட & மருத்துவப் விபரம்',
    fullName: 'முழு பெயர்',
    ageBloodGroup: 'வயது / ரத்த வகை',
    roomNumber: 'பதிவு செய்யப்பட்ட முகவரி',
    medicalNotes: 'மருத்துவ குறிப்புகள்',
    linkedGuardians: 'இணைக்கப்பட்ட பாதுகாவலர்கள்',
    addGuardian: 'பாதுகாவலரைச் சேர்',
    emergencyHistory: 'அவசர சம்பவ வரலாறு',
    expandMap: 'வரைபடத்தை பெரிதாக்கு ⤢',
    minimizeMap: 'வரைபடத்தை சிறிதாக்கு ⤪',
    mapTitle: 'பாதுகாப்பு வரைபடம்',
    roadMap: 'சாலை வரைபடம்',
    satellite: 'செயற்கைக்கோள்',
    darkMode: 'டார்க் மோட்',
    centerGPS: 'GPS மையம்',
    emergencyDetected: 'அவசரநிலை கண்டறியப்பட்டது',
    helpOnTheWay: 'உதவி வருகிறது',
    acceptIncident: 'ஏற்றுக்கொள்',
    markResolved: 'முடிந்தது என குறி',
    statusPending: 'நிலுவையில்',
    statusAccepted: 'ஏற்கப்பட்டது',
    statusResolved: 'தீர்வு காணப்பட்டது',
    activeIncidents: 'செயலில் உள்ள அவசரநிலைகள்',
    portalQuickAccess: 'விரைவு அணுகல்',
    residentPortal: 'குடியிருப்பாளர் போர்டல்',
    securityResponder: 'பாதுகாப்பு போர்டல்',
    guardianPortal: 'பாதுகாவலர் போர்டல்',
    volunteerPortal: 'தன்னார்வலர் போர்டல்',
    caregiverPortal: 'பராமரிப்பாளர் போர்டல்',
    adminPortal: 'நிர்வாக போர்டல்',
    sensorTelemetry: 'IoT ஸ்மார்ட் சென்சார்',
    simulateFall: '⚡ வீழ்ச்சியை உருவகப்படுத்து',
    simulatePulseSpike: '❤️ இதய துடிப்பை உருவகப்படுத்து',
    neighborTagline: 'ஒவ்வொரு நொடியும் முக்கியம். அண்டை வீட்டார் உதவலாம்.',
    signInTitle: 'CareConnect உள்நுழைவு',
    signInSubtitle: 'உங்கள் விவரங்களை உள்ளிடவும்',
    emailLabel: 'மின்னஞ்சல்',
    passwordLabel: 'கடவுச்சொல்',
    loginBtn: 'உள்நுழை',
    alreadyHaveAccount: 'கணக்கு உள்ளதா? உள்நுழை',
    needAccount: 'கணக்கு தேவையா? பதிவு செய்',
    registerBtn: 'பதிவு செய்',
    backToIntro: 'அறிமுகத் திரைக்குத் திரும்பு',
    locating: 'GPS கண்டறியப்படுகிறது...',
    locationOff: 'இருப்பிடம் முடங்கியுள்ளது',
    refreshLocation: 'GPS புதுப்பி',
    enableLocation: 'GPS இயக்கு',
    locationStatus: 'இருப்பிட நிலை',
    addressLabel: 'முகவரி:',
    coordinatesLabel: 'ஆயத்தொலைவுகள்:',
    accuracyLabel: 'துல்லியம்:'
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    dir: 'ltr',
    brandSubtitle: 'リアルタイム緊急通報＆安全管理システム',
    residentSOS: '居住者SOS',
    respondersSecurity: '警備・救護チーム',
    guardians: '保護者・ご家族',
    caregiverRoster: '介護スタッフ名簿',
    adminAnalytics: '管理者アナリティクス',
    neighborPortal: '地域助け合いネットワーク',
    introPage: '🎬 紹介動画',
    aiAssistant: 'AIアシスタント',
    logout: 'ログアウト',
    welcome: 'ようこそ',
    emergencyLocation: '発生場所',
    describeEmergencyPlaceholder: '状況を入力してください（例：浴室で転倒）...',
    aiClassify: 'AI分析',
    triggerSOS: 'SOS発信',
    personalProfile: 'カルテ・基本情報',
    fullName: '氏名',
    ageBloodGroup: '年齢 / 血液型',
    roomNumber: '登録住所',
    medicalNotes: '持病・特記事項',
    linkedGuardians: '緊急連絡先（ご家族）',
    addGuardian: '連絡先を追加',
    emergencyHistory: '緊急対応履歴',
    expandMap: 'マップ拡大 ⤢',
    minimizeMap: 'マップ縮小 ⤪',
    mapTitle: 'リアルタイム安全マップ',
    roadMap: '標準地図',
    satellite: '航空写真',
    darkMode: 'ダークモード',
    centerGPS: '現在地に移動',
    emergencyDetected: '緊急事態発生',
    helpOnTheWay: '救助に向かっています',
    acceptIncident: '対応を開始する',
    markResolved: '対応完了とする',
    statusPending: '対応待ち',
    statusAccepted: '対応中',
    statusResolved: '解決済み',
    activeIncidents: '発生中の緊急案件',
    portalQuickAccess: 'ポータルクイック切替',
    residentPortal: '居住者ポータル',
    securityResponder: '警備・救護ポータル',
    guardianPortal: 'ご家族ポータル',
    volunteerPortal: 'ボランティア',
    caregiverPortal: '介護スタッフ',
    adminPortal: '管理者ポータル',
    sensorTelemetry: 'IoTバイタルセンサー',
    simulateFall: '⚡ 転倒検知テスト',
    simulatePulseSpike: '❤️ 脈拍異常テスト',
    neighborTagline: '一秒を争う命。地域の助け合いが力に。',
    signInTitle: 'CareConnect ログイン',
    signInSubtitle: '役割を選択するかログイン情報を入力してください',
    emailLabel: 'メールアドレス',
    passwordLabel: 'パスワード',
    loginBtn: 'ログイン',
    alreadyHaveAccount: 'アカウントをお持ちの方はこちら',
    needAccount: '新規登録はこちら',
    registerBtn: '新規登録',
    backToIntro: 'イントロ画面に戻る',
    locating: '位置情報を取得中...',
    locationOff: '位置情報オフ',
    refreshLocation: 'GPS再取得',
    enableLocation: '位置情報を有効化',
    locationStatus: '位置情報ステータス',
    addressLabel: '住所:',
    coordinatesLabel: '座標:',
    accuracyLabel: '精度:'
  },
  zh: {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    flag: '🇨🇳',
    dir: 'ltr',
    brandSubtitle: '实时紧急呼叫与安全防护系统',
    residentSOS: '居民 SOS 呼救',
    respondersSecurity: '安保与救援队',
    guardians: '家属 Guardian',
    caregiverRoster: '护理人员名册',
    adminAnalytics: '管理后台分析',
    neighborPortal: '邻里互助网络',
    introPage: '🎬 介绍视频',
    aiAssistant: 'AI 智能助手',
    logout: '退出登录',
    welcome: '欢迎',
    emergencyLocation: '事发地点',
    describeEmergencyPlaceholder: '请描述紧急情况...',
    aiClassify: 'AI 快速分类',
    triggerSOS: '发起 SOS',
    personalProfile: '个人与健康档案',
    fullName: '姓名',
    ageBloodGroup: '年龄 / 血型',
    roomNumber: '登记地址',
    medicalNotes: '病史及注意事项',
    linkedGuardians: '关联紧急联系人',
    addGuardian: '添加联系人',
    emergencyHistory: '历史报警记录',
    expandMap: '放大地图 ⤢',
    minimizeMap: '缩小地图 ⤪',
    mapTitle: '实时安全地图',
    roadMap: '标准路线图',
    satellite: '卫星图',
    darkMode: '暗黑模式',
    centerGPS: '定位至当前点',
    emergencyDetected: '检测到紧急呼救',
    helpOnTheWay: '救援人员正在赶来',
    acceptIncident: '接单救援',
    markResolved: '标记为已完成',
    statusPending: '待处理',
    statusAccepted: '救援中',
    statusResolved: '已解决',
    activeIncidents: '当前紧急案件',
    portalQuickAccess: '快捷入口',
    residentPortal: '居民端',
    securityResponder: '安保端',
    guardianPortal: '家属端',
    volunteerPortal: '志愿者端',
    caregiverPortal: '护理端',
    adminPortal: '管理端',
    sensorTelemetry: 'IoT 智能手环遥测',
    simulateFall: '⚡ 模拟跌倒警报',
    simulatePulseSpike: '❤️ 模拟心率异常',
    neighborTagline: '分秒必争，邻里相助。',
    signInTitle: 'CareConnect 登录',
    signInSubtitle: '选择角色快捷登录或输入账号',
    emailLabel: '邮箱地址',
    passwordLabel: '密码',
    loginBtn: '登录系统',
    alreadyHaveAccount: '已有账号？直接登录',
    needAccount: '没有账号？立即注册',
    registerBtn: '注册',
    backToIntro: '返回介绍页面',
    locating: '正在定位中...',
    locationOff: '未开启定位',
    refreshLocation: '刷新 GPS 定位',
    enableLocation: '开启实时 GPS',
    locationStatus: '定位状态',
    addressLabel: '当前地址:',
    coordinatesLabel: '经纬度:',
    accuracyLabel: '精度:'
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    dir: 'ltr',
    brandSubtitle: '실시간 응급 대응 및 안전 관리 시스템',
    residentSOS: '입주자 SOS',
    respondersSecurity: '보안 및 구조대',
    guardians: '보호자',
    caregiverRoster: '간병인 명단',
    adminAnalytics: '관리자 분석',
    neighborPortal: '이웃 상부상조 네트워크',
    introPage: '🎬 소개 영상',
    aiAssistant: 'AI 비서',
    logout: '로그아웃',
    welcome: '환영합니다',
    emergencyLocation: '응급 발생 위치',
    describeEmergencyPlaceholder: '응급 상황을 입력하세요...',
    aiClassify: 'AI 분류',
    triggerSOS: 'SOS 요청',
    personalProfile: '개인 및 건강 프로필',
    fullName: '성명',
    ageBloodGroup: '연령 / 혈액형',
    roomNumber: '등록 주소',
    medicalNotes: '기저질환 및 메모',
    linkedGuardians: '등록된 비상 연락처',
    addGuardian: '보호자 추가',
    emergencyHistory: '응급 신고 이력',
    expandMap: '지도 확대 ⤢',
    minimizeMap: '지도 축소 ⤪',
    mapTitle: '실시간 안전 지도',
    roadMap: '일반 지도',
    satellite: '위성 지도',
    darkMode: '다크 모드',
    centerGPS: '내 위치 이동',
    emergencyDetected: '응급 상황 감지',
    helpOnTheWay: '구조대가 이동 중입니다',
    acceptIncident: '신고 수락',
    markResolved: '조치 완료',
    statusPending: '대기 중',
    statusAccepted: '처리 중',
    statusResolved: '완료됨',
    activeIncidents: '진행 중인 응급 사건',
    portalQuickAccess: '빠른 포털 이동',
    residentPortal: '입주자 포털',
    securityResponder: '보안 구조대',
    guardianPortal: '보호자 포털',
    volunteerPortal: '봉사자 포털',
    caregiverPortal: '간병인 포털',
    adminPortal: '관리자 포털',
    sensorTelemetry: 'IoT 스마트 바이탈 센서',
    simulateFall: '⚡ 낙상 시뮬레이션',
    simulatePulseSpike: '❤️ 심박수 이상 시뮬레이션',
    neighborTagline: '1초가 급한 순간, 이웃의 도움이 함께합니다.',
    signInTitle: 'CareConnect 로그인',
    signInSubtitle: '역할을 선택하거나 계정 정보를 입력하세요',
    emailLabel: '이메일 주소',
    passwordLabel: '비밀번호',
    loginBtn: '로그인',
    alreadyHaveAccount: '계정이 있으신가요? 로그인',
    needAccount: '계정이 없으신가요? 회원가입',
    registerBtn: '회원가입',
    backToIntro: '소개 화면으로 이동',
    locating: 'GPS 위치 확인 중...',
    locationOff: '위치 비활성화',
    refreshLocation: 'GPS 새로고침',
    enableLocation: 'GPS 활성화',
    locationStatus: '실시간 위치 상태',
    addressLabel: '주소:',
    coordinatesLabel: '좌표:',
    accuracyLabel: '오차范围:'
  },
  bn: {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'রিয়েল-টাইম জরুরি প্রতিক্রিয়া এবং সুরক্ষা ব্যবস্থা',
    residentSOS: 'আবাসিক এসওএস',
    respondersSecurity: 'প্রতিক্রিয়াকারী এবং নিরাপত্তা',
    guardians: 'অভিভাবক',
    caregiverRoster: 'তত্ত্বাবধায়ক তালিকা',
    adminAnalytics: 'অ্যাডমিন অ্যানালিটিক্স',
    neighborPortal: 'প্রতিবেশী নেটওয়ার্ক',
    introPage: '🎬 পরিচিতি পাতা',
    aiAssistant: 'এআই সহকারী',
    logout: 'লগআউট',
    welcome: 'স্বাগতম',
    emergencyLocation: 'জরুরি অবস্থান',
    describeEmergencyPlaceholder: 'জরুরি অবস্থা বর্ণনা করুন...',
    aiClassify: 'এআই শ্রেণীবিভাগ',
    triggerSOS: 'এসওএস পাঠান',
    personalProfile: 'ব্যক্তিগত এবং চিকিৎসা প্রোফাইল',
    fullName: 'সম্পূর্ণ নাম',
    ageBloodGroup: 'বয়স / রক্তের গ্রুপ',
    roomNumber: 'নিবন্ধিত ঠিকানা',
    medicalNotes: 'চিকিৎসা অবস্থা এবং নোট',
    linkedGuardians: 'সংযুক্ত জরুরি অভিভাবক',
    addGuardian: 'অভিভাবক যোগ করুন',
    emergencyHistory: 'জরুরি ঘটনার ইতিহাস',
    expandMap: 'মানচিত্র বড় করুন ⤢',
    minimizeMap: 'মানচিত্র ছোট করুন ⤪',
    mapTitle: 'লাইভ নিরাপত্তা মানচিত্র',
    roadMap: 'রোডম্যাপ',
    satellite: 'স্যাটেলাইট',
    darkMode: 'ডার্ক মোড',
    centerGPS: 'জিপিএস কেন্দ্র',
    emergencyDetected: 'জরুরি অবস্থা সনাক্ত হয়েছে',
    helpOnTheWay: 'সাহায্য আসছে',
    acceptIncident: 'ঘটনা টিকিট গ্রহণ করুন',
    markResolved: 'সমাধান হয়েছে চিহ্নিত করুন',
    statusPending: 'পেন্ডিং',
    statusAccepted: 'গৃহীত',
    statusResolved: 'সমাধান হয়েছে',
    activeIncidents: 'সক্রিয় জরুরি টিকিট',
    portalQuickAccess: 'সরাসরি পোর্টাল অ্যাক্সেস',
    residentPortal: 'আবাসিক পোর্টাল',
    securityResponder: 'নিরাপত্তা প্রতিক্রিয়াকারী',
    guardianPortal: 'অভিভাবক পোর্টাল',
    volunteerPortal: 'স্বেচ্ছাসেবক পোর্টাল',
    caregiverPortal: 'তত্ত্বাবধায়ক পোর্টাল',
    adminPortal: 'অ্যাডমিন পোর্টাল',
    sensorTelemetry: 'আইওটি স্মার্ট সেন্সর টেলিমেট্রি',
    simulateFall: '⚡ হঠাৎ পতনের সিমুলেশন',
    simulatePulseSpike: '❤️ পালস স্পাইক সিমুলেশন',
    neighborTagline: 'প্রতিটি সেকেন্ড গুরুত্বপূর্ণ। প্রতি প্রতিবেশী সাহায্য করতে পারে।',
    signInTitle: 'কেয়ারকানেক্ট লগইন',
    signInSubtitle: 'একটি পোর্টাল ভূমিকা চয়ন করুন বা লগইন করুন',
    emailLabel: 'ইমেল ঠিকানা',
    passwordLabel: 'পাসওয়ার্ড',
    loginBtn: 'পোর্টালে সাইন ইন করুন',
    alreadyHaveAccount: 'ইতিমধ্যে নিবন্ধিত? লগইন করুন',
    needAccount: 'অ্যাকাউন্ট প্রয়োজন? নিবন্ধন করুন',
    registerBtn: 'নিবন্ধন করুন',
    backToIntro: 'পরিচিতি স্ক্রিনে ফিরে যান',
    locating: 'জিপিএস সনাক্ত করা হচ্ছে...',
    locationOff: 'অবস্থান বন্ধ',
    refreshLocation: 'জিপিএস অবস্থান রিফ্রেশ করুন',
    enableLocation: 'লাইভ জিপিএস চালু করুন',
    locationStatus: 'লাইভ অবস্থানের স্থিতি',
    addressLabel: 'ঠিকানা:',
    coordinatesLabel: 'স্থানাঙ্ক:',
    accuracyLabel: 'সঠিকতা:'
  },
  mr: {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'रिअल-टाइम आपत्कालीन प्रतिसाद आणि सुरक्षा यंत्रणा',
    residentSOS: 'निवासी एसओएस',
    respondersSecurity: 'प्रतिसादक आणि सुरक्षा',
    guardians: 'पालक',
    caregiverRoster: 'काळजीवाहू यादी',
    adminAnalytics: 'अॅडमिन विश्लेषण',
    neighborPortal: 'शेजारी नेटवर्क',
    introPage: '🎬 परिचय पृष्ठ',
    aiAssistant: 'एआय सहाय्यक',
    logout: 'लॉगआउट',
    welcome: 'स्वागत आहे',
    emergencyLocation: 'आपत्कालीन स्थान',
    describeEmergencyPlaceholder: 'आपत्कालीन परिस्थितिचे वर्णन करा...',
    aiClassify: 'एआय वर्गीकरण',
    triggerSOS: 'एसओएस पाठवा',
    personalProfile: 'वैयक्तिक आणि वैद्यकीय प्रोफाइल',
    fullName: 'पूर्ण नाव',
    ageBloodGroup: 'वय / रक्त गट',
    roomNumber: 'नोंदणीकृत पत्ता',
    medicalNotes: 'वैद्यकीय स्थिती आणि नोट्स',
    linkedGuardians: 'लिंक केलेले आपत्कालीन पालक',
    addGuardian: 'पालक जोडा',
    emergencyHistory: 'आपत्कालीन घटनेचा इतिहास',
    expandMap: 'नकाशा मोठा करा ⤢',
    minimizeMap: 'नकाशा लहान करा ⤪',
    mapTitle: 'थेट सुरक्षा नकाशा',
    roadMap: 'रोडमॅप',
    satellite: 'सॅटेलाइट',
    darkMode: 'डार्क मोड',
    centerGPS: 'जीपीएस केंद्र',
    emergencyDetected: 'आपत्कालीन परिस्थिती आढळली',
    helpOnTheWay: 'मदत येत आहे',
    acceptIncident: 'तिकीट स्वीकारा',
    markResolved: 'निवारण झाले म्हणून चिन्हांकित करा',
    statusPending: 'प्रलंबित',
    statusAccepted: 'स्वीकृत',
    statusResolved: 'निवारण झाले',
    activeIncidents: 'सक्रिय आपत्कालीन तिकिटे',
    portalQuickAccess: 'थेट पोर्टल प्रवेश',
    residentPortal: 'निवासी पोर्टल',
    securityResponder: 'सुरक्षा प्रतिसादक',
    guardianPortal: 'पालक पोर्टल',
    volunteerPortal: 'स्वयंसेवक पोर्टल',
    caregiverPortal: 'काळजीवाहू पोर्टल',
    adminPortal: 'अॅडमिन पोर्टल',
    sensorTelemetry: 'आयओटी स्मार्ट सेन्सर टेलिमेट्री',
    simulateFall: '⚡ अचानक पडण्याचे सिम्युलेशन',
    simulatePulseSpike: '❤️ पल्स स्पाइक सिम्युलेशन',
    neighborTagline: 'प्रत्येक सेकंद महत्त्वाचा आहे. प्रत्येक शेजारी मदत करू शकतो.',
    signInTitle: 'केअरकनेक्ट लॉगिन',
    signInSubtitle: 'एक पोर्टल भूमिका निवडा किंवा लॉगिन करा',
    emailLabel: 'ईमेल पत्ता',
    passwordLabel: 'पासवर्ड',
    loginBtn: 'पोर्टलवर साइन इन करा',
    alreadyHaveAccount: 'आधीच नोंदणीकृत आहात? लॉगिन करा',
    needAccount: 'खाते हवे आहे? नोंदणी करा',
    registerBtn: 'नोंदणी करा',
    backToIntro: 'परिचय स्क्रीनवर परत जा',
    locating: 'जीपीएस शोधत आहे...',
    locationOff: 'स्थान बंद आहे',
    refreshLocation: 'जीपीएस स्थान रिफ्रेश करा',
    enableLocation: 'थेट जीपीएस सक्षम करा',
    locationStatus: 'थेट स्थान स्थिती',
    addressLabel: 'पत्ता:',
    coordinatesLabel: 'गुणक:',
    accuracyLabel: 'अचूकता:'
  },
  ml: {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'തത്സമയ അടിയന്തര പ്രതികരണ സുരക്ഷാ സംവിധാനം',
    residentSOS: 'റസിഡന്റ് എസ്.ഒ.എസ്',
    respondersSecurity: 'സുരക്ഷാ ജീവനക്കാർ',
    guardians: 'രക്ഷാകർത്താക്കൾ',
    caregiverRoster: 'കെയർഗിവർ പട്ടിക',
    adminAnalytics: 'അഡ്മിൻ അനലിറ്റിക്സ്',
    neighborPortal: 'അയൽപക്ക ശൃംഖല',
    introPage: '🎬 ആമുഖ പേജ്',
    aiAssistant: 'AI അസിസ്റ്റന്റ്',
    logout: 'ലോഗ് ഔട്ട്',
    welcome: 'സ്വാഗതം',
    emergencyLocation: 'അടിയന്തര സ്ഥലം',
    describeEmergencyPlaceholder: 'അടിയന്തിര സാഹചര്യം വിവരിക്കുക...',
    aiClassify: 'AI വർഗ്ഗീകരണം',
    triggerSOS: 'SOS അയക്കുക',
    personalProfile: 'വ്യക്തിഗത മെഡിക്കൽ പ്രൊഫൈൽ',
    fullName: 'പൂർണ്ണനാമം',
    ageBloodGroup: 'പ്രായം / രക്തഗ്രൂപ്പ്',
    roomNumber: 'രജിസ്റ്റർ ചെയ്ത വിലാസം',
    medicalNotes: 'മെഡിക്കൽ വിവരങ്ങൾ',
    linkedGuardians: 'ബന്ധിപ്പിച്ച രക്ഷാകർത്താക്കൾ',
    addGuardian: 'രക്ഷാകർത്താവിനെ ചേർക്കുക',
    emergencyHistory: 'അടിയന്തര സംഭവ ചരിത്രം',
    expandMap: 'മാപ്പ് വലുതാക്കുക ⤢',
    minimizeMap: 'മാപ്പ് ചെറുതാക്കുക ⤪',
    mapTitle: 'ലൈവ് സുരക്ഷാ മാപ്പ്',
    roadMap: 'റോഡ് മാപ്പ്',
    satellite: 'സാറ്റലൈറ്റ്',
    darkMode: 'ഡാർക്ക് മോഡ്',
    centerGPS: 'ജിപിഎസ് കേന്ദ്രീകരിക്കുക',
    emergencyDetected: 'അടിയന്തിരാവസ്ഥ കണ്ടെത്തി',
    helpOnTheWay: 'സഹായം ഉടൻ എത്തും',
    acceptIncident: 'കേസ് സ്വീകരിക്കുക',
    markResolved: 'പരിഹരിച്ചതായി അടയാളപ്പെടുത്തുക',
    statusPending: 'പെൻഡിംഗ്',
    statusAccepted: 'സ്വീകരിച്ചു',
    statusResolved: 'പരിഹരിച്ചു',
    activeIncidents: 'സജീവ അടിയന്തര കേസുകൾ',
    portalQuickAccess: 'ഡയറക്റ്റ് പോർട്ടൽ ആക്സസ്',
    residentPortal: 'റസിഡന്റ് പോർട്ടൽ',
    securityResponder: 'സെക്യൂരിറ്റി റെസ്പോണ്ടർ',
    guardianPortal: 'രക്ഷാകർത്താവ് പോർട്ടൽ',
    volunteerPortal: 'വോളണ്ടിയർ പോർട്ടൽ',
    caregiverPortal: 'കെയർഗിവർ പോർട്ടൽ',
    adminPortal: 'അഡ്മിൻ പോർട്ടಲ್',
    sensorTelemetry: 'IoT സ്മാർട്ട് സെൻസർ',
    simulateFall: '⚡ വീഴ്ച അനുകരിക്കുക',
    simulatePulseSpike: '❤️ പൾസ് വർദ്ധനവ് അനുകരിക്കുക',
    neighborTagline: 'ഓരോ നിമിഷവും പ്രധാനം. ഓരോ അയൽക്കാരനും സഹായിക്കാം.',
    signInTitle: 'കെയർകണക്ട് ലോഗിൻ',
    signInSubtitle: 'ഒരു പോർട്ടൽ റോൾ തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ ലോഗിൻ ചെയ്യുക',
    emailLabel: 'ഇമെയിൽ വിലാസം',
    passwordLabel: 'പാസ്‌വേഡ്',
    loginBtn: 'ലോഗിൻ ചെയ്യുക',
    alreadyHaveAccount: 'അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യുക',
    needAccount: 'അക്കൗണ്ട് ഇല്ലേ? രജിസ്റ്റർ ചെയ്യുക',
    registerBtn: 'രജിസ്റ്റർ ചെയ്യുക',
    backToIntro: 'ആമുഖ സ്ക്രീനിലേക്ക് മടങ്ങുക',
    locating: 'ജിപിഎസ് കണ്ടെത്തുന്നു...',
    locationOff: 'ലൊക്കേഷൻ ഓഫാണ്',
    refreshLocation: 'ജിപിഎസ് പുതുക്കുക',
    enableLocation: 'ലൈവ് ജിപിഎസ് സജീവമാക്കുക',
    locationStatus: 'ലൈവ് ലൊക്കേഷൻ നില',
    addressLabel: 'വിലാസം:',
    coordinatesLabel: 'കോർഡിനേറ്റുകൾ:',
    accuracyLabel: 'കൃത്യത:'
  },
  kn: {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    dir: 'ltr',
    brandSubtitle: 'ನೈಜ-ಸಮಯದ ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಸುರಕ್ಷತೆ ವ್ಯವಸ್ಥೆ',
    residentSOS: 'ನಿವಾಸಿ ಎಸ್‌ಒಎಸ್',
    respondersSecurity: 'ಪ್ರತಿಕ್ರಿಯೆದಾರರು ಮತ್ತು ಭದ್ರತೆ',
    guardians: 'ಪೋಷಕರು',
    caregiverRoster: 'ಪಾಲನೆದಾರರ ಪಟ್ಟಿ',
    adminAnalytics: 'ಅಡ್ಮಿನ್ ವಿಶ್ಲೇಷಣೆ',
    neighborPortal: 'ನೆರೆಹೊರೆಯ ನೆಟ್‌ವರ್ಕ್',
    introPage: '🎬 ಪರಿಚಯ ಪುಟ',
    aiAssistant: 'AI ಸಹಾಯಕ',
    logout: 'ಲಾಗ್ ಔಟ್',
    welcome: 'ಸ್ವಾಗತ',
    emergencyLocation: 'ತುರ್ತು ಸ್ಥಳ',
    describeEmergencyPlaceholder: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿಯನ್ನು ವಿವರಿಸಿ...',
    aiClassify: 'AI ವರ್ಗೀಕರಣ',
    triggerSOS: 'SOS ಕಳುಹಿಸಿ',
    personalProfile: 'ವೈಯಕ್ತಿಕ ಮತ್ತು ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    ageBloodGroup: 'ವಯಸ್ಸು / ರಕ್ತದ ಗುಂಪು',
    roomNumber: 'ನೋಂದಾಯಿತ ವಿಳಾಸ',
    medicalNotes: 'ವೈದ್ಯಕೀಯ ಪರಿಸ್ಥಿತಿ ಮತ್ತು ಟಿಪ್ಪಣಿಗಳು',
    linkedGuardians: 'ಲಿಂಕ್ ಮಾಡಲಾದ ತುರ್ತು ಪೋಷಕರು',
    addGuardian: 'ಪೋಷಕರನ್ನು ಸೇರಿಸಿ',
    emergencyHistory: 'ತುರ್ತು ಘಟನೆ ಇತಿಹಾಸ',
    expandMap: 'ನಕ್ಷೆ ವಿಸ್ತರಿಸಿ ⤢',
    minimizeMap: 'ನಕ್ಷೆ ಕುಗ್ಗಿಸಿ ⤪',
    mapTitle: 'ಲೈವ್ ಸುರಕ್ಷತಾ ನಕ್ಷೆ',
    roadMap: 'ರೋಡ್‌ಮ್ಯಾಪ್',
    satellite: 'ಉಪಗ್ರಹ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    centerGPS: 'GPS ಕೇಂದ್ರ',
    emergencyDetected: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಪತ್ತೆಯಾಗಿದೆ',
    helpOnTheWay: 'ಸಹಾಯ ಬರುತ್ತಿದೆ',
    acceptIncident: 'ಟಿಕೆಟ್ ಸ್ವೀಕರಿಸಿ',
    markResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    statusPending: 'ಬಾಕಿ ಉಳಿದಿದೆ',
    statusAccepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    statusResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    activeIncidents: 'ಸಕ್ರಿಯ ತುರ್ತು ಟಿಕೆಟ್‌ಗಳು',
    portalQuickAccess: 'ನೇರ ಪೋರ್ಟಲ್ ಪ್ರವೇಶ',
    residentPortal: 'ನಿವಾಸಿ ಪೋರ್ಟಲ್',
    securityResponder: 'ಭದ್ರತಾ ಪ್ರತಿಕ್ರಿಯೆದಾರ',
    guardianPortal: 'ಪೋಷಕರ ಪೋರ್ಟಲ್',
    volunteerPortal: 'ಸ್ವಯಂಸೇವಕ ಪೋರ್ಟಲ್',
    caregiverPortal: 'ಪಾಲನೆದಾರರ ಪೋರ್ಟಲ್',
    adminPortal: 'ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್',
    sensorTelemetry: 'IoT ಸ್ಮಾರ್ಟ್ ಸೆನ್ಸರ್ ಟೆಲಿಮೆಟ್ರಿ',
    simulateFall: '⚡ ಹಠಾತ್ ಪತನದ ಸಿಮ್ಯುಲೇಶನ್',
    simulatePulseSpike: '❤️ ನಾಡಿ ಸ್ಪೈಕ್ ಸಿಮ್ಯಲೇಶನ್',
    neighborTagline: 'ಪ್ರತಿ ಸೆಕೆಂಡು ಮುಖ್ಯ. ಪ್ರತಿ ನೆರೆಹೊರೆಯವರು ಸಹಾಯ ಮಾಡಬಹುದು.',
    signInTitle: 'ಕೇರ್ ಕನೆಕ್ಟ್ ಲಾಗಿನ್',
    signInSubtitle: 'ಪೋರ್ಟಲ್ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ಲಾಗಿನ್ ಮಾಡಿ',
    emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ',
    passwordLabel: 'ಪಾಸ್‌ವರ್ಡ್',
    loginBtn: 'ಪೋರ್ಟಲ್‌ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
    needAccount: 'ಖಾತೆಯ ಅಗತ್ಯವಿದೆಯೇ? ನೋಂದಾಯಿಸಿ',
    registerBtn: 'ನೋಂದಾಯಿಸಿ',
    backToIntro: 'ಪರಿಚಯ ಪರದೆಗೆ ಹಿಂತಿರುಗಿ',
    locating: 'GPS ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    locationOff: 'ಸ್ಥಳ ಆಫ್ ಆಗಿದೆ',
    refreshLocation: 'GPS ಸ್ಥಳ ರಿಫ್ರೆಶ್ ಮಾಡಿ',
    enableLocation: 'ಲೈವ್ GPS ಸಕ್ರಿಯಗೊಳಿಸಿ',
    locationStatus: 'ಲೈವ್ ಸ್ಥಳ ಸ್ಥಿತಿ',
    addressLabel: 'ವಿಳಾಸ:',
    coordinatesLabel: 'ನಿರ್ದೇಶಾಂಕಗಳು:',
    accuracyLabel: 'ನಿಖರತೆ:'
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    dir: 'ltr',
    brandSubtitle: 'Sistema de respuesta a emergencias y seguridad residencial',
    residentSOS: 'SOS Residente',
    respondersSecurity: 'Rescatistas y Seguridad',
    guardians: 'Tutores',
    caregiverRoster: 'Lista de Cuidadores',
    adminAnalytics: 'Panel de Administración',
    neighborPortal: 'Red de Vecinos',
    introPage: '🎬 Página de Introducción',
    aiAssistant: 'Asistente de IA',
    logout: 'Cerrar Sesión',
    welcome: 'Bienvenido',
    emergencyLocation: 'Ubicación de Emergencia',
    describeEmergencyPlaceholder: 'Describa la emergencia (ej. Caída en el baño)...',
    aiClassify: 'Clasificar con IA',
    triggerSOS: 'SOS',
    personalProfile: 'Perfil Personal y Médico',
    fullName: 'Nombre Completo',
    ageBloodGroup: 'Edad / Grupo Sanguíneo',
    roomNumber: 'Dirección Registrada',
    medicalNotes: 'Condiciones Médicas y Notas',
    linkedGuardians: 'Tutores de Emergencia Vinculados',
    addGuardian: 'Añadir Tutor',
    emergencyHistory: 'Historial de Incidentes',
    expandMap: 'Expandir Mapa ⤢',
    minimizeMap: 'Minimizar Mapa ⤪',
    mapTitle: 'Mapa de Seguridad en Vivo',
    roadMap: 'Mapa',
    satellite: 'Satélite',
    darkMode: 'Modo Oscuro',
    centerGPS: 'Centrar GPS',
    emergencyDetected: 'EMERGENCIA DETECTADA',
    helpOnTheWay: 'AYUDA EN CAMINO',
    acceptIncident: 'Aceptar Incidente',
    markResolved: 'Marcar como Resuelto',
    statusPending: 'PENDIENTE',
    statusAccepted: 'ACEPTADO',
    statusResolved: 'RESUELTO',
    activeIncidents: 'Casos Activos de Emergencia',
    portalQuickAccess: 'Acceso Rápido al Portal',
    residentPortal: 'Portal de Residente',
    securityResponder: 'Rescatista de Seguridad',
    guardianPortal: 'Portal del Tutor',
    volunteerPortal: 'Portal de Voluntario',
    caregiverPortal: 'Portal del Cuidador',
    adminPortal: 'Portal de Admin',
    sensorTelemetry: 'Telemetría del Sensor Inteligente IoT',
    simulateFall: '⚡ Simular Caída Repentina',
    simulatePulseSpike: '❤️ Simular Pico de Pulso',
    neighborTagline: 'Cada segundo cuenta. Cada vecino puede ayudar.',
    signInTitle: 'Inicio de Sesión CareConnect',
    signInSubtitle: 'Seleccione un rol de portal o inicie sesión con credenciales',
    emailLabel: 'Correo Electrónico',
    passwordLabel: 'Contraseña',
    loginBtn: 'Iniciar Sesión en el Portal',
    alreadyHaveAccount: '¿Ya estás registrado? Inicia sesión',
    needAccount: '¿Necesitas una cuenta? Regístrate',
    registerBtn: 'Registrarse',
    backToIntro: 'Volver a la Pantalla de Inicio',
    locating: 'Localizando GPS...',
    locationOff: 'Ubicación Desactivada',
    refreshLocation: 'Actualizar Ubicación GPS',
    enableLocation: 'Activar GPS en Vivo',
    locationStatus: 'Estado de Ubicación en Vivo',
    addressLabel: 'Dirección:',
    coordinatesLabel: 'Coordenadas:',
    accuracyLabel: 'Precisión:'
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    dir: 'ltr',
    brandSubtitle: 'Système de sécurité et d\'intervention d\'urgence en temps réel',
    residentSOS: 'SOS Résident',
    respondersSecurity: 'Intervenants & Sécurité',
    guardians: 'Tuteurs',
    caregiverRoster: 'Liste des Soignants',
    adminAnalytics: 'Analyses Administrateur',
    neighborPortal: 'Réseau de Voisins',
    introPage: '🎬 Page d\'Introduction',
    aiAssistant: 'Assistant IA',
    logout: 'Se Déconnecter',
    welcome: 'Bienvenue',
    emergencyLocation: 'Lieu de l\'Urgence',
    describeEmergencyPlaceholder: 'Décrivez l\'urgence (ex. Chute dans la salle de bain)...',
    aiClassify: 'Classifier avec l\'IA',
    triggerSOS: 'SOS',
    personalProfile: 'Profil Personnel & Médical',
    fullName: 'Nom Complet',
    ageBloodGroup: 'Âge / Groupe Sanguin',
    roomNumber: 'Adresse Enregistrée',
    medicalNotes: 'Notes & Conditions Médicales',
    linkedGuardians: 'Tuteurs d\'Urgence Liés',
    addGuardian: 'Ajouter un Tuteur',
    emergencyHistory: 'Historique des Incidents',
    expandMap: 'Agrandir la Carte ⤢',
    minimizeMap: 'Réduire la Carte ⤪',
    mapTitle: 'Carte de Sécurité en Direct',
    roadMap: 'Carte',
    satellite: 'Satellite',
    darkMode: 'Mode Sombre',
    centerGPS: 'Centrer le GPS',
    emergencyDetected: 'URGENCE DÉTECTÉE',
    helpOnTheWay: 'AIDE EN ROUTE',
    acceptIncident: 'Accepter l\'Incident',
    markResolved: 'Marquer comme Résolu',
    statusPending: 'EN ATTENTE',
    statusAccepted: 'ACCEPTÉ',
    statusResolved: 'RÉSOLU',
    activeIncidents: 'Urgences Actives',
    portalQuickAccess: 'Accès Direct au Portail',
    residentPortal: 'Portail Résident',
    securityResponder: 'Intervenant de Sécurité',
    guardianPortal: 'Portail Tuteur',
    volunteerPortal: 'Portail Bénévole',
    caregiverPortal: 'Portail Soignant',
    adminPortal: 'Portail Admin',
    sensorTelemetry: 'Télémétrie du Capteur Intelligent IoT',
    simulateFall: '⚡ Simuler une Chute Soudaine',
    simulatePulseSpike: '❤️ Simuler un Pic de Pouls',
    neighborTagline: 'Chaque seconde compte. Chaque voisin peut aider.',
    signInTitle: 'Connexion CareConnect',
    signInSubtitle: 'Sélectionnez un rôle ou connectez-vous',
    emailLabel: 'Adresse E-mail',
    passwordLabel: 'Mot de passe',
    loginBtn: 'Se connecter au portail',
    alreadyHaveAccount: 'Déjà inscrit ? Se connecter',
    needAccount: 'Besoin d\'un compte ? S\'inscrire',
    registerBtn: 'S\'inscrire',
    backToIntro: 'Retour à l\'écran d\'accueil',
    locating: 'Recherche GPS...',
    locationOff: 'Localisation Désactivée',
    refreshLocation: 'Actualiser la position GPS',
    enableLocation: 'Activer le GPS en direct',
    locationStatus: 'État de la localisation en direct',
    addressLabel: 'Adresse :',
    coordinatesLabel: 'Coordonnées :',
    accuracyLabel: 'Précision :'
  },
  de: {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    dir: 'ltr',
    brandSubtitle: 'Echtzeit-Notfallreaktions- und Sicherheitssystem',
    residentSOS: 'Bewohner SOS',
    respondersSecurity: 'Einsatzkräfte & Sicherheit',
    guardians: 'Vormünder',
    caregiverRoster: 'Pflegerliste',
    adminAnalytics: 'Admin-Analysen',
    neighborPortal: 'Nachbarschaftsnetzwerk',
    introPage: '🎬 Einführungsseite',
    aiAssistant: 'KI-Assistent',
    logout: 'Abmelden',
    welcome: 'Willkommen',
    emergencyLocation: 'Notfallort',
    describeEmergencyPlaceholder: 'Notfall beschreiben (z.B. Sturz im Bad)...',
    aiClassify: 'KI Klassifizieren',
    triggerSOS: 'SOS',
    personalProfile: 'Persönliches & Medizinisches Profil',
    fullName: 'Vollständiger Name',
    ageBloodGroup: 'Alter / Blutgruppe',
    roomNumber: 'Registrierte Adresse',
    medicalNotes: 'Medizinische Bedingungen & Notizen',
    linkedGuardians: 'Verknüpfte Notfallkontakte',
    addGuardian: 'Kontakt Hinzufügen',
    emergencyHistory: 'Notfallverlauf',
    expandMap: 'Karte Vergrößern ⤢',
    minimizeMap: 'Karte Verkleinern ⤪',
    mapTitle: 'Live-Sicherheitskarte',
    roadMap: 'Straßenkarte',
    satellite: 'Satellit',
    darkMode: 'Dunkelmodus',
    centerGPS: 'GPS Zentrieren',
    emergencyDetected: 'NOTFALL ERKANNT',
    helpOnTheWay: 'HILFE IST UNTERWEGS',
    acceptIncident: 'Ticket Akzeptieren',
    markResolved: 'Als Gelöst Markieren',
    statusPending: 'AUSSTEHEND',
    statusAccepted: 'AKZEPTIERT',
    statusResolved: 'GELÖST',
    activeIncidents: 'Aktive Notfälle',
    portalQuickAccess: 'Direkter Portalzugriff',
    residentPortal: 'Bewohner-Portal',
    securityResponder: 'Sicherheits-Einsatzkraft',
    guardianPortal: 'Angehörigen-Portal',
    volunteerPortal: 'Freiwilligen-Portal',
    caregiverPortal: 'Pfleger-Portal',
    adminPortal: 'Admin-Portal',
    sensorTelemetry: 'IoT-Sensortelemetrie',
    simulateFall: '⚡ Sturz Simulieren',
    simulatePulseSpike: '❤️ Pulsschlag-Spike Simulieren',
    neighborTagline: 'Jede Sekunde zählt. Jeder Nachbar kann helfen.',
    signInTitle: 'CareConnect Login',
    signInSubtitle: 'Rolle auswählen oder mit Anmeldedaten anmelden',
    emailLabel: 'E-Mail-Adresse',
    passwordLabel: 'Passwort',
    loginBtn: 'Im Portal Anmelden',
    alreadyHaveAccount: 'Bereits registriert? Einloggen',
    needAccount: 'Konto benötigt? Registrieren',
    registerBtn: 'Registrieren',
    backToIntro: 'Zurück zum Startbildschirm',
    locating: 'GPS-Ortung...',
    locationOff: 'Ortung Deaktiviert',
    refreshLocation: 'GPS Aktualisieren',
    enableLocation: 'Live-GPS Aktivieren',
    locationStatus: 'Live-Ortungsstatus',
    addressLabel: 'Adresse:',
    coordinatesLabel: 'Koordinaten:',
    accuracyLabel: 'Genauigkeit:'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('careconnect_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('careconnect_lang', lang);
    const currentDict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    document.documentElement.dir = currentDict.dir || 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, currentLangObj: TRANSLATIONS[lang] || TRANSLATIONS.en }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
